# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JungleG
brief-intro: Since We Are Young
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jungleg.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  JungleG
email: msy1260@sina.com
weibo_username: 3936199667
zhihu_username: pu-ti-shu-76-24
linkedIn_username: 
dribbble_username:

description_footer: 我们的生命中断之日，才是我们的激情终止之时。

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: 
gitment_shortname: usualname

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 2531ea6523c5830b18e5317e5679871a
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt 摘要分割
excerpt_separator: '<!-- more -->'

# paginate
gems: [jekyll-paginate]
paginate: 6
